using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using GUI_NhaKhoa.BLL_NhaKhoa;
namespace GUI_NhaKhoa
{
    public partial class frmTiepDonBenhNhan : Form
    {
        BLLTiepDonBenhNhan tiepDonBenhNhan = new BLLTiepDonBenhNhan();
        public string TiepDon { get; set; }
        public frmTiepDonBenhNhan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            cbbMaBN.Properties.DataSource = new GUI_NhaKhoa.BLL_NhaKhoa.QuanLyNhaKhoaDataContext().BenhNhans;
        }

        private void frmTiepDonBenhNhan_Load(object sender, EventArgs e)
        {
            //cbbMaBN.Properties.DataSource = tiepDonBenhNhan.LayBenhNhan();
            //cbbMaBN.Properties.DisplayMember = "Mã BN";
            //cbbMaBN.Properties.ValueMember = "Mã BN";
        }

        private void btnThemBN_Click(object sender, EventArgs e)
        {
            frmQuanLyBenhNhan benhNhan = new frmQuanLyBenhNhan();
            benhNhan.Text = "Thêm mới bệnh nhân";
            benhNhan.ShowDialog();
            
        }

        private void frmTiepDonBenhNhan_Load_1(object sender, EventArgs e)
        {
           
            cbbMaBN.Properties.DataSource = tiepDonBenhNhan.LayBenhNhan();
            cbbMaBN.Properties.DisplayMember = "MaBenhNhan";
            cbbMaBN.Properties.ValueMember = "MaBenhNhan";
            txtTiepDon.Text = TiepDon;
            cbbNgayKham.Text = DateTime.Now.ToString("dd/MM/yyyy");
        }

        private void cbbLoaiKham_TextChanged(object sender, EventArgs e)
        {
            if (cbbLoaiKham.Text == "Tái khám")
            {
                btnThemBN.Enabled = false;
            }
            else
                btnThemBN.Enabled = true;
        }

        private void cbbMaBN_TextChanged(object sender, EventArgs e)
        {
            tiepDonBenhNhan.LayTTBenhNhan(cbbMaBN.Text, txtMaThe, txtHoTen, cbbGioiTinh, txtNgaySinh, txtDiaChi, txtSDT);
        }
    }
}
