#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_NhaKhoa.BLL_NhaKhoa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyNhaKhoa")]
	public partial class QuanLyNhaKhoaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertManHinh(ManHinh instance);
    partial void UpdateManHinh(ManHinh instance);
    partial void DeleteManHinh(ManHinh instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNguoiDungNhomNguoiDung(NguoiDungNhomNguoiDung instance);
    partial void UpdateNguoiDungNhomNguoiDung(NguoiDungNhomNguoiDung instance);
    partial void DeleteNguoiDungNhomNguoiDung(NguoiDungNhomNguoiDung instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhomNguoiDung(NhomNguoiDung instance);
    partial void UpdateNhomNguoiDung(NhomNguoiDung instance);
    partial void DeleteNhomNguoiDung(NhomNguoiDung instance);
    partial void InsertPhanQuyen(PhanQuyen instance);
    partial void UpdatePhanQuyen(PhanQuyen instance);
    partial void DeletePhanQuyen(PhanQuyen instance);
    partial void InsertBenhNhan(BenhNhan instance);
    partial void UpdateBenhNhan(BenhNhan instance);
    partial void DeleteBenhNhan(BenhNhan instance);
    partial void InsertPhongKham(PhongKham instance);
    partial void UpdatePhongKham(PhongKham instance);
    partial void DeletePhongKham(PhongKham instance);
    partial void InsertTiepDonBenhNhan(TiepDonBenhNhan instance);
    partial void UpdateTiepDonBenhNhan(TiepDonBenhNhan instance);
    partial void DeleteTiepDonBenhNhan(TiepDonBenhNhan instance);
    partial void InsertPhieuKhamBenh(PhieuKhamBenh instance);
    partial void UpdatePhieuKhamBenh(PhieuKhamBenh instance);
    partial void DeletePhieuKhamBenh(PhieuKhamBenh instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertLoaiDichVu(LoaiDichVu instance);
    partial void UpdateLoaiDichVu(LoaiDichVu instance);
    partial void DeleteLoaiDichVu(LoaiDichVu instance);
    partial void InsertCTPhieuDichVu(CTPhieuDichVu instance);
    partial void UpdateCTPhieuDichVu(CTPhieuDichVu instance);
    partial void DeleteCTPhieuDichVu(CTPhieuDichVu instance);
    partial void InsertPhieuDichVu(PhieuDichVu instance);
    partial void UpdatePhieuDichVu(PhieuDichVu instance);
    partial void DeletePhieuDichVu(PhieuDichVu instance);
    partial void InsertPhieuKetQua(PhieuKetQua instance);
    partial void UpdatePhieuKetQua(PhieuKetQua instance);
    partial void DeletePhieuKetQua(PhieuKetQua instance);
    #endregion
		
		public QuanLyNhaKhoaDataContext() : 
				base(global::GUI_NhaKhoa.Properties.Settings.Default.QuanLyNhaKhoaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaKhoaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaKhoaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaKhoaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaKhoaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ManHinh> ManHinhs
		{
			get
			{
				return this.GetTable<ManHinh>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDungNhomNguoiDung> NguoiDungNhomNguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDungNhomNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhomNguoiDung> NhomNguoiDungs
		{
			get
			{
				return this.GetTable<NhomNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyen> PhanQuyens
		{
			get
			{
				return this.GetTable<PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<BenhNhan> BenhNhans
		{
			get
			{
				return this.GetTable<BenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<PhongKham> PhongKhams
		{
			get
			{
				return this.GetTable<PhongKham>();
			}
		}
		
		public System.Data.Linq.Table<TiepDonBenhNhan> TiepDonBenhNhans
		{
			get
			{
				return this.GetTable<TiepDonBenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<PhieuKhamBenh> PhieuKhamBenhs
		{
			get
			{
				return this.GetTable<PhieuKhamBenh>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDichVu> LoaiDichVus
		{
			get
			{
				return this.GetTable<LoaiDichVu>();
			}
		}
		
		public System.Data.Linq.Table<CTPhieuDichVu> CTPhieuDichVus
		{
			get
			{
				return this.GetTable<CTPhieuDichVu>();
			}
		}
		
		public System.Data.Linq.Table<PhieuDichVu> PhieuDichVus
		{
			get
			{
				return this.GetTable<PhieuDichVu>();
			}
		}
		
		public System.Data.Linq.Table<PhieuKetQua> PhieuKetQuas
		{
			get
			{
				return this.GetTable<PhieuKetQua>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManHinh")]
	public partial class ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaManHinh;
		
		private string _TenManHinh;
		
		private EntitySet<PhanQuyen> _PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnTenManHinhChanging(string value);
    partial void OnTenManHinhChanged();
    #endregion
		
		public ManHinh()
		{
			this._PhanQuyens = new EntitySet<PhanQuyen>(new Action<PhanQuyen>(this.attach_PhanQuyens), new Action<PhanQuyen>(this.detach_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenManHinh
		{
			get
			{
				return this._TenManHinh;
			}
			set
			{
				if ((this._TenManHinh != value))
				{
					this.OnTenManHinhChanging(value);
					this.SendPropertyChanging();
					this._TenManHinh = value;
					this.SendPropertyChanged("TenManHinh");
					this.OnTenManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_PhanQuyen", Storage="_PhanQuyens", ThisKey="MaManHinh", OtherKey="MaManHinh")]
		public EntitySet<PhanQuyen> PhanQuyens
		{
			get
			{
				return this._PhanQuyens;
			}
			set
			{
				this._PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = this;
		}
		
		private void detach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _TrangThai;
		
		private EntitySet<NguoiDungNhomNguoiDung> _NguoiDungNhomNguoiDungs;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public NguoiDung()
		{
			this._NguoiDungNhomNguoiDungs = new EntitySet<NguoiDungNhomNguoiDung>(new Action<NguoiDungNhomNguoiDung>(this.attach_NguoiDungNhomNguoiDungs), new Action<NguoiDungNhomNguoiDung>(this.detach_NguoiDungNhomNguoiDungs));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(20)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NguoiDungNhomNguoiDung", Storage="_NguoiDungNhomNguoiDungs", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<NguoiDungNhomNguoiDung> NguoiDungNhomNguoiDungs
		{
			get
			{
				return this._NguoiDungNhomNguoiDungs;
			}
			set
			{
				this._NguoiDungNhomNguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NguoiDung", Storage="_NhanVien", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungNhomNguoiDungs(NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_NguoiDungNhomNguoiDungs(NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDungNhomNguoiDung")]
	public partial class NguoiDungNhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MaNhom;
		
		private string _GhiChu;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<NhomNguoiDung> _NhomNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NguoiDungNhomNguoiDung()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._NhomNguoiDung = default(EntityRef<NhomNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NguoiDungNhomNguoiDung", Storage="_NguoiDung", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.NguoiDungNhomNguoiDungs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.NguoiDungNhomNguoiDungs.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_NguoiDungNhomNguoiDung", Storage="_NhomNguoiDung", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomNguoiDung NhomNguoiDung
		{
			get
			{
				return this._NhomNguoiDung.Entity;
			}
			set
			{
				NhomNguoiDung previousValue = this._NhomNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NhomNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomNguoiDung.Entity = null;
						previousValue.NguoiDungNhomNguoiDungs.Remove(this);
					}
					this._NhomNguoiDung.Entity = value;
					if ((value != null))
					{
						value.NguoiDungNhomNguoiDungs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _HoTen;
		
		private string _Phai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<System.DateTime> _NgayVaoLam;
		
		private System.Nullable<int> _LuongCoBan;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
		private EntitySet<TiepDonBenhNhan> _TiepDonBenhNhans;
		
		private EntitySet<TiepDonBenhNhan> _TiepDonBenhNhans1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnPhaiChanging(string value);
    partial void OnPhaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnNgayVaoLamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoLamChanged();
    partial void OnLuongCoBanChanging(System.Nullable<int> value);
    partial void OnLuongCoBanChanged();
    #endregion
		
		public NhanVien()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			this._TiepDonBenhNhans = new EntitySet<TiepDonBenhNhan>(new Action<TiepDonBenhNhan>(this.attach_TiepDonBenhNhans), new Action<TiepDonBenhNhan>(this.detach_TiepDonBenhNhans));
			this._TiepDonBenhNhans1 = new EntitySet<TiepDonBenhNhan>(new Action<TiepDonBenhNhan>(this.attach_TiepDonBenhNhans1), new Action<TiepDonBenhNhan>(this.detach_TiepDonBenhNhans1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phai", DbType="NVarChar(4)")]
		public string Phai
		{
			get
			{
				return this._Phai;
			}
			set
			{
				if ((this._Phai != value))
				{
					this.OnPhaiChanging(value);
					this.SendPropertyChanging();
					this._Phai = value;
					this.SendPropertyChanged("Phai");
					this.OnPhaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoLam
		{
			get
			{
				return this._NgayVaoLam;
			}
			set
			{
				if ((this._NgayVaoLam != value))
				{
					this.OnNgayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoLam = value;
					this.SendPropertyChanged("NgayVaoLam");
					this.OnNgayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCoBan", DbType="Int")]
		public System.Nullable<int> LuongCoBan
		{
			get
			{
				return this._LuongCoBan;
			}
			set
			{
				if ((this._LuongCoBan != value))
				{
					this.OnLuongCoBanChanging(value);
					this.SendPropertyChanging();
					this._LuongCoBan = value;
					this.SendPropertyChanged("LuongCoBan");
					this.OnLuongCoBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NguoiDung", Storage="_NguoiDungs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TiepDonBenhNhan", Storage="_TiepDonBenhNhans", ThisKey="MaNhanVien", OtherKey="BacSi")]
		public EntitySet<TiepDonBenhNhan> TiepDonBenhNhans
		{
			get
			{
				return this._TiepDonBenhNhans;
			}
			set
			{
				this._TiepDonBenhNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TiepDonBenhNhan1", Storage="_TiepDonBenhNhans1", ThisKey="MaNhanVien", OtherKey="NhanVienTiepDon")]
		public EntitySet<TiepDonBenhNhan> TiepDonBenhNhans1
		{
			get
			{
				return this._TiepDonBenhNhans1;
			}
			set
			{
				this._TiepDonBenhNhans1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TiepDonBenhNhans(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TiepDonBenhNhans(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TiepDonBenhNhans1(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = this;
		}
		
		private void detach_TiepDonBenhNhans1(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomNguoiDung")]
	public partial class NhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private string _GhiChu;
		
		private EntitySet<NguoiDungNhomNguoiDung> _NguoiDungNhomNguoiDungs;
		
		private EntitySet<PhanQuyen> _PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NhomNguoiDung()
		{
			this._NguoiDungNhomNguoiDungs = new EntitySet<NguoiDungNhomNguoiDung>(new Action<NguoiDungNhomNguoiDung>(this.attach_NguoiDungNhomNguoiDungs), new Action<NguoiDungNhomNguoiDung>(this.detach_NguoiDungNhomNguoiDungs));
			this._PhanQuyens = new EntitySet<PhanQuyen>(new Action<PhanQuyen>(this.attach_PhanQuyens), new Action<PhanQuyen>(this.detach_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_NguoiDungNhomNguoiDung", Storage="_NguoiDungNhomNguoiDungs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<NguoiDungNhomNguoiDung> NguoiDungNhomNguoiDungs
		{
			get
			{
				return this._NguoiDungNhomNguoiDungs;
			}
			set
			{
				this._NguoiDungNhomNguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_PhanQuyen", Storage="_PhanQuyens", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<PhanQuyen> PhanQuyens
		{
			get
			{
				return this._PhanQuyens;
			}
			set
			{
				this._PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungNhomNguoiDungs(NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = this;
		}
		
		private void detach_NguoiDungNhomNguoiDungs(NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = null;
		}
		
		private void attach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = this;
		}
		
		private void detach_PhanQuyens(PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyen")]
	public partial class PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _MaManHinh;
		
		private bool _CoQuyen;
		
		private EntityRef<ManHinh> _ManHinh;
		
		private EntityRef<NhomNguoiDung> _NhomNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnCoQuyenChanging(bool value);
    partial void OnCoQuyenChanged();
    #endregion
		
		public PhanQuyen()
		{
			this._ManHinh = default(EntityRef<ManHinh>);
			this._NhomNguoiDung = default(EntityRef<NhomNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					if (this._ManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuyen", DbType="Bit NOT NULL")]
		public bool CoQuyen
		{
			get
			{
				return this._CoQuyen;
			}
			set
			{
				if ((this._CoQuyen != value))
				{
					this.OnCoQuyenChanging(value);
					this.SendPropertyChanging();
					this._CoQuyen = value;
					this.SendPropertyChanged("CoQuyen");
					this.OnCoQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_PhanQuyen", Storage="_ManHinh", ThisKey="MaManHinh", OtherKey="MaManHinh", IsForeignKey=true)]
		public ManHinh ManHinh
		{
			get
			{
				return this._ManHinh.Entity;
			}
			set
			{
				ManHinh previousValue = this._ManHinh.Entity;
				if (((previousValue != value) 
							|| (this._ManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ManHinh.Entity = null;
						previousValue.PhanQuyens.Remove(this);
					}
					this._ManHinh.Entity = value;
					if ((value != null))
					{
						value.PhanQuyens.Add(this);
						this._MaManHinh = value.MaManHinh;
					}
					else
					{
						this._MaManHinh = default(string);
					}
					this.SendPropertyChanged("ManHinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_PhanQuyen", Storage="_NhomNguoiDung", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomNguoiDung NhomNguoiDung
		{
			get
			{
				return this._NhomNguoiDung.Entity;
			}
			set
			{
				NhomNguoiDung previousValue = this._NhomNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NhomNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomNguoiDung.Entity = null;
						previousValue.PhanQuyens.Remove(this);
					}
					this._NhomNguoiDung.Entity = value;
					if ((value != null))
					{
						value.PhanQuyens.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan")]
	public partial class BenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBenhNhan;
		
		private string _MaThe;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private EntitySet<TiepDonBenhNhan> _TiepDonBenhNhans;
		
		private EntitySet<PhieuDichVu> _PhieuDichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    partial void OnMaTheChanging(string value);
    partial void OnMaTheChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public BenhNhan()
		{
			this._TiepDonBenhNhans = new EntitySet<TiepDonBenhNhan>(new Action<TiepDonBenhNhan>(this.attach_TiepDonBenhNhans), new Action<TiepDonBenhNhan>(this.detach_TiepDonBenhNhans));
			this._PhieuDichVus = new EntitySet<PhieuDichVu>(new Action<PhieuDichVu>(this.attach_PhieuDichVus), new Action<PhieuDichVu>(this.detach_PhieuDichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThe", DbType="VarChar(10)")]
		public string MaThe
		{
			get
			{
				return this._MaThe;
			}
			set
			{
				if ((this._MaThe != value))
				{
					this.OnMaTheChanging(value);
					this.SendPropertyChanging();
					this._MaThe = value;
					this.SendPropertyChanged("MaThe");
					this.OnMaTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(4)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_TiepDonBenhNhan", Storage="_TiepDonBenhNhans", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan")]
		public EntitySet<TiepDonBenhNhan> TiepDonBenhNhans
		{
			get
			{
				return this._TiepDonBenhNhans;
			}
			set
			{
				this._TiepDonBenhNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_PhieuDichVu", Storage="_PhieuDichVus", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan")]
		public EntitySet<PhieuDichVu> PhieuDichVus
		{
			get
			{
				return this._PhieuDichVus;
			}
			set
			{
				this._PhieuDichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TiepDonBenhNhans(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_TiepDonBenhNhans(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
		
		private void attach_PhieuDichVus(PhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_PhieuDichVus(PhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongKham")]
	public partial class PhongKham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhong;
		
		private string _TenPhong;
		
		private EntitySet<TiepDonBenhNhan> _TiepDonBenhNhans;
		
		private EntitySet<PhieuDichVu> _PhieuDichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnTenPhongChanging(string value);
    partial void OnTenPhongChanged();
    #endregion
		
		public PhongKham()
		{
			this._TiepDonBenhNhans = new EntitySet<TiepDonBenhNhan>(new Action<TiepDonBenhNhan>(this.attach_TiepDonBenhNhans), new Action<TiepDonBenhNhan>(this.detach_TiepDonBenhNhans));
			this._PhieuDichVus = new EntitySet<PhieuDichVu>(new Action<PhieuDichVu>(this.attach_PhieuDichVus), new Action<PhieuDichVu>(this.detach_PhieuDichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhong", DbType="NVarChar(50)")]
		public string TenPhong
		{
			get
			{
				return this._TenPhong;
			}
			set
			{
				if ((this._TenPhong != value))
				{
					this.OnTenPhongChanging(value);
					this.SendPropertyChanging();
					this._TenPhong = value;
					this.SendPropertyChanged("TenPhong");
					this.OnTenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongKham_TiepDonBenhNhan", Storage="_TiepDonBenhNhans", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<TiepDonBenhNhan> TiepDonBenhNhans
		{
			get
			{
				return this._TiepDonBenhNhans;
			}
			set
			{
				this._TiepDonBenhNhans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongKham_PhieuDichVu", Storage="_PhieuDichVus", ThisKey="MaPhong", OtherKey="MaPhong")]
		public EntitySet<PhieuDichVu> PhieuDichVus
		{
			get
			{
				return this._PhieuDichVus;
			}
			set
			{
				this._PhieuDichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TiepDonBenhNhans(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.PhongKham = this;
		}
		
		private void detach_TiepDonBenhNhans(TiepDonBenhNhan entity)
		{
			this.SendPropertyChanging();
			entity.PhongKham = null;
		}
		
		private void attach_PhieuDichVus(PhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.PhongKham = this;
		}
		
		private void detach_PhieuDichVus(PhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.PhongKham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TiepDonBenhNhan")]
	public partial class TiepDonBenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoPhieu;
		
		private System.DateTime _NgayKham;
		
		private string _LoaiKham;
		
		private string _LyDoKham;
		
		private string _TieuDuong;
		
		private string _BenhTimMach;
		
		private string _HuyetAp;
		
		private string _TinhTrang;
		
		private string _MaBenhNhan;
		
		private string _MaPhong;
		
		private string _NhanVienTiepDon;
		
		private string _BacSi;
		
		private EntityRef<PhieuKhamBenh> _PhieuKhamBenh;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
		private EntityRef<NhanVien> _NhanVien1;
		
		private EntityRef<PhongKham> _PhongKham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPhieuChanging(string value);
    partial void OnSoPhieuChanged();
    partial void OnNgayKhamChanging(System.DateTime value);
    partial void OnNgayKhamChanged();
    partial void OnLoaiKhamChanging(string value);
    partial void OnLoaiKhamChanged();
    partial void OnLyDoKhamChanging(string value);
    partial void OnLyDoKhamChanged();
    partial void OnTieuDuongChanging(string value);
    partial void OnTieuDuongChanged();
    partial void OnBenhTimMachChanging(string value);
    partial void OnBenhTimMachChanged();
    partial void OnHuyetApChanging(string value);
    partial void OnHuyetApChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnNhanVienTiepDonChanging(string value);
    partial void OnNhanVienTiepDonChanged();
    partial void OnBacSiChanging(string value);
    partial void OnBacSiChanged();
    #endregion
		
		public TiepDonBenhNhan()
		{
			this._PhieuKhamBenh = default(EntityRef<PhieuKhamBenh>);
			this._NhanVien = default(EntityRef<NhanVien>);
			this._BenhNhan = default(EntityRef<BenhNhan>);
			this._NhanVien1 = default(EntityRef<NhanVien>);
			this._PhongKham = default(EntityRef<PhongKham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this.OnSoPhieuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieu = value;
					this.SendPropertyChanged("SoPhieu");
					this.OnSoPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date NOT NULL")]
		public System.DateTime NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKham", DbType="NVarChar(50)")]
		public string LoaiKham
		{
			get
			{
				return this._LoaiKham;
			}
			set
			{
				if ((this._LoaiKham != value))
				{
					this.OnLoaiKhamChanging(value);
					this.SendPropertyChanging();
					this._LoaiKham = value;
					this.SendPropertyChanged("LoaiKham");
					this.OnLoaiKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDoKham", DbType="NVarChar(50)")]
		public string LyDoKham
		{
			get
			{
				return this._LyDoKham;
			}
			set
			{
				if ((this._LyDoKham != value))
				{
					this.OnLyDoKhamChanging(value);
					this.SendPropertyChanging();
					this._LyDoKham = value;
					this.SendPropertyChanged("LyDoKham");
					this.OnLyDoKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDuong", DbType="NVarChar(20)")]
		public string TieuDuong
		{
			get
			{
				return this._TieuDuong;
			}
			set
			{
				if ((this._TieuDuong != value))
				{
					this.OnTieuDuongChanging(value);
					this.SendPropertyChanging();
					this._TieuDuong = value;
					this.SendPropertyChanged("TieuDuong");
					this.OnTieuDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BenhTimMach", DbType="NVarChar(20)")]
		public string BenhTimMach
		{
			get
			{
				return this._BenhTimMach;
			}
			set
			{
				if ((this._BenhTimMach != value))
				{
					this.OnBenhTimMachChanging(value);
					this.SendPropertyChanging();
					this._BenhTimMach = value;
					this.SendPropertyChanged("BenhTimMach");
					this.OnBenhTimMachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HuyetAp", DbType="NVarChar(20)")]
		public string HuyetAp
		{
			get
			{
				return this._HuyetAp;
			}
			set
			{
				if ((this._HuyetAp != value))
				{
					this.OnHuyetApChanging(value);
					this.SendPropertyChanging();
					this._HuyetAp = value;
					this.SendPropertyChanged("HuyetAp");
					this.OnHuyetApChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._PhongKham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienTiepDon", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NhanVienTiepDon
		{
			get
			{
				return this._NhanVienTiepDon;
			}
			set
			{
				if ((this._NhanVienTiepDon != value))
				{
					if (this._NhanVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhanVienTiepDonChanging(value);
					this.SendPropertyChanging();
					this._NhanVienTiepDon = value;
					this.SendPropertyChanged("NhanVienTiepDon");
					this.OnNhanVienTiepDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BacSi", DbType="VarChar(10)")]
		public string BacSi
		{
			get
			{
				return this._BacSi;
			}
			set
			{
				if ((this._BacSi != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBacSiChanging(value);
					this.SendPropertyChanging();
					this._BacSi = value;
					this.SendPropertyChanged("BacSi");
					this.OnBacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiepDonBenhNhan_PhieuKhamBenh", Storage="_PhieuKhamBenh", ThisKey="SoPhieu", OtherKey="SoPhieu", IsUnique=true, IsForeignKey=false)]
		public PhieuKhamBenh PhieuKhamBenh
		{
			get
			{
				return this._PhieuKhamBenh.Entity;
			}
			set
			{
				PhieuKhamBenh previousValue = this._PhieuKhamBenh.Entity;
				if (((previousValue != value) 
							|| (this._PhieuKhamBenh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuKhamBenh.Entity = null;
						previousValue.TiepDonBenhNhan = null;
					}
					this._PhieuKhamBenh.Entity = value;
					if ((value != null))
					{
						value.TiepDonBenhNhan = this;
					}
					this.SendPropertyChanged("PhieuKhamBenh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TiepDonBenhNhan", Storage="_NhanVien", ThisKey="BacSi", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TiepDonBenhNhans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TiepDonBenhNhans.Add(this);
						this._BacSi = value.MaNhanVien;
					}
					else
					{
						this._BacSi = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_TiepDonBenhNhan", Storage="_BenhNhan", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.TiepDonBenhNhans.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.TiepDonBenhNhans.Add(this);
						this._MaBenhNhan = value.MaBenhNhan;
					}
					else
					{
						this._MaBenhNhan = default(string);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TiepDonBenhNhan1", Storage="_NhanVien1", ThisKey="NhanVienTiepDon", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien1
		{
			get
			{
				return this._NhanVien1.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien1.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien1.Entity = null;
						previousValue.TiepDonBenhNhans1.Remove(this);
					}
					this._NhanVien1.Entity = value;
					if ((value != null))
					{
						value.TiepDonBenhNhans1.Add(this);
						this._NhanVienTiepDon = value.MaNhanVien;
					}
					else
					{
						this._NhanVienTiepDon = default(string);
					}
					this.SendPropertyChanged("NhanVien1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongKham_TiepDonBenhNhan", Storage="_PhongKham", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public PhongKham PhongKham
		{
			get
			{
				return this._PhongKham.Entity;
			}
			set
			{
				PhongKham previousValue = this._PhongKham.Entity;
				if (((previousValue != value) 
							|| (this._PhongKham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongKham.Entity = null;
						previousValue.TiepDonBenhNhans.Remove(this);
					}
					this._PhongKham.Entity = value;
					if ((value != null))
					{
						value.TiepDonBenhNhans.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("PhongKham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuKhamBenh")]
	public partial class PhieuKhamBenh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoPhieu;
		
		private string _ChuanDoan;
		
		private string _KetLuan;
		
		private EntitySet<PhieuDichVu> _PhieuDichVus;
		
		private EntityRef<TiepDonBenhNhan> _TiepDonBenhNhan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPhieuChanging(string value);
    partial void OnSoPhieuChanged();
    partial void OnChuanDoanChanging(string value);
    partial void OnChuanDoanChanged();
    partial void OnKetLuanChanging(string value);
    partial void OnKetLuanChanged();
    #endregion
		
		public PhieuKhamBenh()
		{
			this._PhieuDichVus = new EntitySet<PhieuDichVu>(new Action<PhieuDichVu>(this.attach_PhieuDichVus), new Action<PhieuDichVu>(this.detach_PhieuDichVus));
			this._TiepDonBenhNhan = default(EntityRef<TiepDonBenhNhan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					if (this._TiepDonBenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoPhieuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieu = value;
					this.SendPropertyChanged("SoPhieu");
					this.OnSoPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuanDoan", DbType="NVarChar(225)")]
		public string ChuanDoan
		{
			get
			{
				return this._ChuanDoan;
			}
			set
			{
				if ((this._ChuanDoan != value))
				{
					this.OnChuanDoanChanging(value);
					this.SendPropertyChanging();
					this._ChuanDoan = value;
					this.SendPropertyChanged("ChuanDoan");
					this.OnChuanDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetLuan", DbType="NVarChar(225) NOT NULL", CanBeNull=false)]
		public string KetLuan
		{
			get
			{
				return this._KetLuan;
			}
			set
			{
				if ((this._KetLuan != value))
				{
					this.OnKetLuanChanging(value);
					this.SendPropertyChanging();
					this._KetLuan = value;
					this.SendPropertyChanged("KetLuan");
					this.OnKetLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKhamBenh_PhieuDichVu", Storage="_PhieuDichVus", ThisKey="SoPhieu", OtherKey="SoPhieu")]
		public EntitySet<PhieuDichVu> PhieuDichVus
		{
			get
			{
				return this._PhieuDichVus;
			}
			set
			{
				this._PhieuDichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TiepDonBenhNhan_PhieuKhamBenh", Storage="_TiepDonBenhNhan", ThisKey="SoPhieu", OtherKey="SoPhieu", IsForeignKey=true)]
		public TiepDonBenhNhan TiepDonBenhNhan
		{
			get
			{
				return this._TiepDonBenhNhan.Entity;
			}
			set
			{
				TiepDonBenhNhan previousValue = this._TiepDonBenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._TiepDonBenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TiepDonBenhNhan.Entity = null;
						previousValue.PhieuKhamBenh = null;
					}
					this._TiepDonBenhNhan.Entity = value;
					if ((value != null))
					{
						value.PhieuKhamBenh = this;
						this._SoPhieu = value.SoPhieu;
					}
					else
					{
						this._SoPhieu = default(string);
					}
					this.SendPropertyChanged("TiepDonBenhNhan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDichVus(PhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKhamBenh = this;
		}
		
		private void detach_PhieuDichVus(PhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.PhieuKhamBenh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private System.Nullable<int> _DonGia;
		
		private string _DonViTinh;
		
		private string _MaLoai;
		
		private EntitySet<CTPhieuDichVu> _CTPhieuDichVus;
		
		private EntityRef<LoaiDichVu> _LoaiDichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnDonGiaChanging(System.Nullable<int> value);
    partial void OnDonGiaChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    #endregion
		
		public DichVu()
		{
			this._CTPhieuDichVus = new EntitySet<CTPhieuDichVu>(new Action<CTPhieuDichVu>(this.attach_CTPhieuDichVus), new Action<CTPhieuDichVu>(this.detach_CTPhieuDichVus));
			this._LoaiDichVu = default(EntityRef<LoaiDichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(100)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LoaiDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_CTPhieuDichVu", Storage="_CTPhieuDichVus", ThisKey="MaDV", OtherKey="MaDV")]
		public EntitySet<CTPhieuDichVu> CTPhieuDichVus
		{
			get
			{
				return this._CTPhieuDichVus;
			}
			set
			{
				this._CTPhieuDichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDichVu_DichVu", Storage="_LoaiDichVu", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiDichVu LoaiDichVu
		{
			get
			{
				return this._LoaiDichVu.Entity;
			}
			set
			{
				LoaiDichVu previousValue = this._LoaiDichVu.Entity;
				if (((previousValue != value) 
							|| (this._LoaiDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiDichVu.Entity = null;
						previousValue.DichVus.Remove(this);
					}
					this._LoaiDichVu.Entity = value;
					if ((value != null))
					{
						value.DichVus.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("LoaiDichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPhieuDichVus(CTPhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_CTPhieuDichVus(CTPhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDichVu")]
	public partial class LoaiDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<DichVu> _DichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LoaiDichVu()
		{
			this._DichVus = new EntitySet<DichVu>(new Action<DichVu>(this.attach_DichVus), new Action<DichVu>(this.detach_DichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDichVu_DichVu", Storage="_DichVus", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<DichVu> DichVus
		{
			get
			{
				return this._DichVus;
			}
			set
			{
				this._DichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DichVus(DichVu entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDichVu = this;
		}
		
		private void detach_DichVus(DichVu entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTPhieuDichVu")]
	public partial class CTPhieuDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoPhieuDV;
		
		private string _MaDV;
		
		private EntityRef<DichVu> _DichVu;
		
		private EntityRef<PhieuDichVu> _PhieuDichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPhieuDVChanging(string value);
    partial void OnSoPhieuDVChanged();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    #endregion
		
		public CTPhieuDichVu()
		{
			this._DichVu = default(EntityRef<DichVu>);
			this._PhieuDichVu = default(EntityRef<PhieuDichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuDV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPhieuDV
		{
			get
			{
				return this._SoPhieuDV;
			}
			set
			{
				if ((this._SoPhieuDV != value))
				{
					if (this._PhieuDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoPhieuDVChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuDV = value;
					this.SendPropertyChanged("SoPhieuDV");
					this.OnSoPhieuDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_CTPhieuDichVu", Storage="_DichVu", ThisKey="MaDV", OtherKey="MaDV", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.CTPhieuDichVus.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.CTPhieuDichVus.Add(this);
						this._MaDV = value.MaDV;
					}
					else
					{
						this._MaDV = default(string);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDichVu_CTPhieuDichVu", Storage="_PhieuDichVu", ThisKey="SoPhieuDV", OtherKey="SoPhieuDV", IsForeignKey=true)]
		public PhieuDichVu PhieuDichVu
		{
			get
			{
				return this._PhieuDichVu.Entity;
			}
			set
			{
				PhieuDichVu previousValue = this._PhieuDichVu.Entity;
				if (((previousValue != value) 
							|| (this._PhieuDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuDichVu.Entity = null;
						previousValue.CTPhieuDichVus.Remove(this);
					}
					this._PhieuDichVu.Entity = value;
					if ((value != null))
					{
						value.CTPhieuDichVus.Add(this);
						this._SoPhieuDV = value.SoPhieuDV;
					}
					else
					{
						this._SoPhieuDV = default(string);
					}
					this.SendPropertyChanged("PhieuDichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuDichVu")]
	public partial class PhieuDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoPhieuDV;
		
		private string _MaBenhNhan;
		
		private string _MaPhong;
		
		private System.DateTime _NgayLap;
		
		private string _TinhTrang;
		
		private System.Nullable<int> _TongTien;
		
		private string _ThanhToan;
		
		private string _SoPhieu;
		
		private EntitySet<CTPhieuDichVu> _CTPhieuDichVus;
		
		private EntitySet<PhieuKetQua> _PhieuKetQuas;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
		private EntityRef<PhieuKhamBenh> _PhieuKhamBenh;
		
		private EntityRef<PhongKham> _PhongKham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPhieuDVChanging(string value);
    partial void OnSoPhieuDVChanged();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    partial void OnMaPhongChanging(string value);
    partial void OnMaPhongChanged();
    partial void OnNgayLapChanging(System.DateTime value);
    partial void OnNgayLapChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    partial void OnThanhToanChanging(string value);
    partial void OnThanhToanChanged();
    partial void OnSoPhieuChanging(string value);
    partial void OnSoPhieuChanged();
    #endregion
		
		public PhieuDichVu()
		{
			this._CTPhieuDichVus = new EntitySet<CTPhieuDichVu>(new Action<CTPhieuDichVu>(this.attach_CTPhieuDichVus), new Action<CTPhieuDichVu>(this.detach_CTPhieuDichVus));
			this._PhieuKetQuas = new EntitySet<PhieuKetQua>(new Action<PhieuKetQua>(this.attach_PhieuKetQuas), new Action<PhieuKetQua>(this.detach_PhieuKetQuas));
			this._BenhNhan = default(EntityRef<BenhNhan>);
			this._PhieuKhamBenh = default(EntityRef<PhieuKhamBenh>);
			this._PhongKham = default(EntityRef<PhongKham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuDV", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPhieuDV
		{
			get
			{
				return this._SoPhieuDV;
			}
			set
			{
				if ((this._SoPhieuDV != value))
				{
					this.OnSoPhieuDVChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuDV = value;
					this.SendPropertyChanged("SoPhieuDV");
					this.OnSoPhieuDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaPhong
		{
			get
			{
				return this._MaPhong;
			}
			set
			{
				if ((this._MaPhong != value))
				{
					if (this._PhongKham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhongChanging(value);
					this.SendPropertyChanging();
					this._MaPhong = value;
					this.SendPropertyChanged("MaPhong");
					this.OnMaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date NOT NULL")]
		public System.DateTime NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(20)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhToan", DbType="NVarChar(20)")]
		public string ThanhToan
		{
			get
			{
				return this._ThanhToan;
			}
			set
			{
				if ((this._ThanhToan != value))
				{
					this.OnThanhToanChanging(value);
					this.SendPropertyChanging();
					this._ThanhToan = value;
					this.SendPropertyChanged("ThanhToan");
					this.OnThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="VarChar(10)")]
		public string SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					if (this._PhieuKhamBenh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoPhieuChanging(value);
					this.SendPropertyChanging();
					this._SoPhieu = value;
					this.SendPropertyChanged("SoPhieu");
					this.OnSoPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDichVu_CTPhieuDichVu", Storage="_CTPhieuDichVus", ThisKey="SoPhieuDV", OtherKey="SoPhieuDV")]
		public EntitySet<CTPhieuDichVu> CTPhieuDichVus
		{
			get
			{
				return this._CTPhieuDichVus;
			}
			set
			{
				this._CTPhieuDichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDichVu_PhieuKetQua", Storage="_PhieuKetQuas", ThisKey="SoPhieuDV", OtherKey="SoPhieuDV")]
		public EntitySet<PhieuKetQua> PhieuKetQuas
		{
			get
			{
				return this._PhieuKetQuas;
			}
			set
			{
				this._PhieuKetQuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_PhieuDichVu", Storage="_BenhNhan", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.PhieuDichVus.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.PhieuDichVus.Add(this);
						this._MaBenhNhan = value.MaBenhNhan;
					}
					else
					{
						this._MaBenhNhan = default(string);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuKhamBenh_PhieuDichVu", Storage="_PhieuKhamBenh", ThisKey="SoPhieu", OtherKey="SoPhieu", IsForeignKey=true)]
		public PhieuKhamBenh PhieuKhamBenh
		{
			get
			{
				return this._PhieuKhamBenh.Entity;
			}
			set
			{
				PhieuKhamBenh previousValue = this._PhieuKhamBenh.Entity;
				if (((previousValue != value) 
							|| (this._PhieuKhamBenh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuKhamBenh.Entity = null;
						previousValue.PhieuDichVus.Remove(this);
					}
					this._PhieuKhamBenh.Entity = value;
					if ((value != null))
					{
						value.PhieuDichVus.Add(this);
						this._SoPhieu = value.SoPhieu;
					}
					else
					{
						this._SoPhieu = default(string);
					}
					this.SendPropertyChanged("PhieuKhamBenh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongKham_PhieuDichVu", Storage="_PhongKham", ThisKey="MaPhong", OtherKey="MaPhong", IsForeignKey=true)]
		public PhongKham PhongKham
		{
			get
			{
				return this._PhongKham.Entity;
			}
			set
			{
				PhongKham previousValue = this._PhongKham.Entity;
				if (((previousValue != value) 
							|| (this._PhongKham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongKham.Entity = null;
						previousValue.PhieuDichVus.Remove(this);
					}
					this._PhongKham.Entity = value;
					if ((value != null))
					{
						value.PhieuDichVus.Add(this);
						this._MaPhong = value.MaPhong;
					}
					else
					{
						this._MaPhong = default(string);
					}
					this.SendPropertyChanged("PhongKham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTPhieuDichVus(CTPhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDichVu = this;
		}
		
		private void detach_CTPhieuDichVus(CTPhieuDichVu entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDichVu = null;
		}
		
		private void attach_PhieuKetQuas(PhieuKetQua entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDichVu = this;
		}
		
		private void detach_PhieuKetQuas(PhieuKetQua entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuKetQua")]
	public partial class PhieuKetQua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoPhieuKQ;
		
		private string _TenDV;
		
		private string _SoPhieuDV;
		
		private string _HinhAnh;
		
		private string _KetLuan;
		
		private EntityRef<PhieuDichVu> _PhieuDichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoPhieuKQChanging(string value);
    partial void OnSoPhieuKQChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnSoPhieuDVChanging(string value);
    partial void OnSoPhieuDVChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnKetLuanChanging(string value);
    partial void OnKetLuanChanged();
    #endregion
		
		public PhieuKetQua()
		{
			this._PhieuDichVu = default(EntityRef<PhieuDichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuKQ", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoPhieuKQ
		{
			get
			{
				return this._SoPhieuKQ;
			}
			set
			{
				if ((this._SoPhieuKQ != value))
				{
					this.OnSoPhieuKQChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuKQ = value;
					this.SendPropertyChanged("SoPhieuKQ");
					this.OnSoPhieuKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(100)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuDV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SoPhieuDV
		{
			get
			{
				return this._SoPhieuDV;
			}
			set
			{
				if ((this._SoPhieuDV != value))
				{
					if (this._PhieuDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoPhieuDVChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuDV = value;
					this.SendPropertyChanged("SoPhieuDV");
					this.OnSoPhieuDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetLuan", DbType="NVarChar(50)")]
		public string KetLuan
		{
			get
			{
				return this._KetLuan;
			}
			set
			{
				if ((this._KetLuan != value))
				{
					this.OnKetLuanChanging(value);
					this.SendPropertyChanging();
					this._KetLuan = value;
					this.SendPropertyChanged("KetLuan");
					this.OnKetLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDichVu_PhieuKetQua", Storage="_PhieuDichVu", ThisKey="SoPhieuDV", OtherKey="SoPhieuDV", IsForeignKey=true)]
		public PhieuDichVu PhieuDichVu
		{
			get
			{
				return this._PhieuDichVu.Entity;
			}
			set
			{
				PhieuDichVu previousValue = this._PhieuDichVu.Entity;
				if (((previousValue != value) 
							|| (this._PhieuDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuDichVu.Entity = null;
						previousValue.PhieuKetQuas.Remove(this);
					}
					this._PhieuDichVu.Entity = value;
					if ((value != null))
					{
						value.PhieuKetQuas.Add(this);
						this._SoPhieuDV = value.SoPhieuDV;
					}
					else
					{
						this._SoPhieuDV = default(string);
					}
					this.SendPropertyChanged("PhieuDichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
